apiVersion: v1
kind: Service
metadata:
  name: customers
spec:
  selector:
    app: customers
  type: NodePort
  internalTrafficPolicy: Local
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 31001
      targetPort: 8080
